#!/bin/sh

set -e

BUILD_DIR=`pwd`/build-dir

NGINX_DIR=`ls nginx-*.tar.gz | sed 's/^\(nginx-.*\)\.tar\.gz$/\1/g'`
PCRE_DIR=`ls pcre-*.tar.gz | sed 's/^\(pcre-.*\)\.tar\.gz$/\1/g'`
ZLIB_DIR=`ls zlib-*.tar.gz | sed 's/^\(zlib-.*\)\.tar\.gz$/\1/g'`

tar xzf pcre-*.tar.gz
tar xzf nginx-*.tar.gz
tar xzf zlib-*.tar.gz

cd ${NGINX_DIR}
./configure --prefix=${BUILD_DIR} --with-pcre=../${PCRE_DIR} --with-zlib=../${ZLIB_DIR} --with-ipv6
make
make install
