#!/bin/sh

set -e

TARGET_DIR=$1

NGINX_DIR=nginx-${NGINX_VERSION}
PCRE_DIR=pcre-${PCRE_VERSION}
ZLIB_DIR=zlib-${ZLIB_VERSION}

tar xzf nginx-${NGINX_VERSION}.tar.gz
tar xzf pcre-${PCRE_VERSION}.tar.gz
tar xzf zlib-${ZLIB_VERSION}.tar.gz

cd ${NGINX_DIR}
./configure \
    --prefix=${TARGET_DIR} \
    --with-pcre=../${PCRE_DIR} \
    --with-zlib=../${ZLIB_DIR} \
    --with-ipv6
make
make install
