#!/bin/sh

set -e

BUILD_DIR=`pwd`/build-dir
INSTALL_DIR=$1
NGINX_DIR=$INSTALL_DIR/vendor/nginx

mkdir -p $NGINX_DIR
cp -rT $BUILD_DIR $NGINX_DIR

mkdir -p $INSTALL_DIR/bin
echo '#!/bin/sh

set -e

SCRIPT_PATH=`readlink -f $0`
SCRIPT_DIR=`dirname $SCRIPT_PATH`
INSTALL_DIR=`dirname $SCRIPT_DIR`

NGINX_DIR=$INSTALL_DIR/vendor/nginx

$NGINX_DIR/sbin/nginx -p $NGINX_DIR "$@"
' > $INSTALL_DIR/bin/nginx
chmod +x $INSTALL_DIR/bin/nginx

